Repository multiversx/mx-chain-rosetta, pull requests merged in 2022-10, with the labels that each got.

#50 Add transaction metadata. Make some operation types more explicit.
  go.mod
  go.sum
  server/provider/errors.go
  server/provider/nodeStatus.go
  server/provider/nodeStatus_test.go
  server/services/blockService_test.go
  server/services/mempoolService_test.go
  server/services/operations.go
  server/services/transactionMetadata.go
  server/services/transactionMetadata_test.go
  server/services/transactionsTransformer.go
  server/services/transactionsTransformer_test.go
  version/constants.go
Labels: type:improvement

#52 Workaround (quick fix) to support construction of cross-shard transactions
  server/services/constructionService.go
  server/services/constructionService_test.go
Labels: type:bug

#53 linter and grammar fixes
  README.md
  server/factory/components/disabledExternalConnector.go
  server/factory/controllers.go
  server/factory/interface.go
  server/factory/provider.go
  server/provider/constants.go
  server/provider/errors.go
  server/provider/networkProvider.go
  server/services/networkProviderExtension_test.go
  server/services/offline_services.go
  server/services/transactionsTransformer.go
  server/services/transactionsTransformer_test.go
  testscommon/addresses.go
  testscommon/networkProviderMock.go
  testscommon/observerFacadeMock.go
Labels: cleanup

#55 Get extra details from node/status and return them in Rosetta API
  cmd/rosetta/cli.go
  cmd/rosetta/main.go
  server/factory/interface.go
  server/factory/provider.go
  server/provider/networkProvider.go
  server/provider/networkProvider_test.go
  server/provider/nodeStatus.go
  server/provider/nodeStatus_test.go
  server/resources/network.go
  server/services/constants.go
  server/services/interface.go
  server/services/networkService.go
  server/services/networkService_test.go
  testscommon/networkProviderMock.go
  version/constants.go
Labels: type:improvement

#56 Add middleware version in response of "/network/options".
  server/services/networkService.go
  server/services/networkService_test.go
  version/constants.go
Labels: type:improvement
